//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderedItems
    {
        public int OrderItemId { get; set; }
        public int OrderId { get; set; }
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public decimal PricePerItem { get; set; }
        public int Quantity { get; set; }
        public decimal TotalPrice { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        public virtual Tbl_Orders Tbl_Orders { get; set; }
    }
}
