//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmoothWear.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Orders()
        {
            this.Tbl_OrderedItems = new HashSet<Tbl_OrderedItems>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserEmail { get; set; }
        public string PhoneNo { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string PreferredPickupSlot { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentStatus { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderedItems> Tbl_OrderedItems { get; set; }
    }
}
